#!/usr/bin/env bash
# ============================================================
# FIX-R EC2 AI Server — Full Setup Script
# Ubuntu 22.04 LTS (x86_64 or arm64)
# Run as root or with sudo: sudo bash setup.sh
# ============================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── 0. Preflight ─────────────────────────────────────────────
[[ $EUID -ne 0 ]] && error "Run as root: sudo bash setup.sh"
[[ -f /etc/lsb-release ]] || error "This script is for Ubuntu only."

info "FIX-R EC2 AI Server setup starting..."

# ── 1. System packages ────────────────────────────────────────
info "Updating system packages..."
apt-get update -qq
apt-get install -y -qq curl wget gnupg2 nginx certbot python3-certbot-nginx ufw fail2ban openssl

# ── 2. Install Ollama ─────────────────────────────────────────
if command -v ollama &>/dev/null; then
  warn "Ollama already installed, skipping."
else
  info "Installing Ollama..."
  curl -fsSL https://ollama.com/install.sh | sh
fi

# Enable & start Ollama service
systemctl enable ollama
systemctl start ollama
sleep 3
info "Ollama is running."

# ── 3. Generate API key ───────────────────────────────────────
API_KEY_FILE="/etc/fixr/api.key"
mkdir -p /etc/fixr

if [[ -f "$API_KEY_FILE" ]]; then
  API_KEY=$(cat "$API_KEY_FILE")
  warn "Existing API key found, reusing it."
else
  API_KEY="fixr-$(openssl rand -hex 24)"
  echo "$API_KEY" > "$API_KEY_FILE"
  chmod 600 "$API_KEY_FILE"
  info "Generated new API key."
fi

# ── 4. Nginx configuration ────────────────────────────────────
info "Configuring Nginx..."

cat > /etc/nginx/sites-available/fixr-ai << NGINXCONF
# FIX-R AI Proxy — generated by setup.sh
# Proxies /v1/* to local Ollama with Bearer token auth

limit_req_zone \$binary_remote_addr zone=fixr_ai:10m rate=20r/m;

server {
    listen 80;
    server_name _;

    # Health check (no auth required)
    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }

    # All other traffic — require Bearer token
    location /v1/ {
        # Rate limiting
        limit_req zone=fixr_ai burst=10 nodelay;

        # API key validation
        if (\$http_authorization != "Bearer ${API_KEY}") {
            return 401 '{"error":"Unauthorized"}';
        }

        proxy_pass         http://127.0.0.1:11434;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   Connection        "";

        # Streaming support
        proxy_buffering        off;
        proxy_cache            off;
        chunked_transfer_encoding on;

        # Generous timeout for long inference
        proxy_read_timeout     300s;
        proxy_connect_timeout  10s;
        proxy_send_timeout     300s;

        add_header X-Served-By "FIX-R-EC2" always;
    }

    location / {
        return 404 '{"error":"Not found"}';
    }
}
NGINXCONF

# Enable site
ln -sf /etc/nginx/sites-available/fixr-ai /etc/nginx/sites-enabled/fixr-ai
rm -f /etc/nginx/sites-enabled/default

nginx -t && systemctl reload nginx
info "Nginx configured and reloaded."

# ── 5. Firewall ────────────────────────────────────────────────
info "Configuring firewall..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp   comment "SSH"
ufw allow 80/tcp   comment "HTTP (Nginx)"
ufw allow 443/tcp  comment "HTTPS (Nginx)"
ufw --force enable
info "Firewall enabled (ports 22, 80, 443 open)."

# ── 6. Fail2ban ────────────────────────────────────────────────
info "Enabling fail2ban..."
systemctl enable fail2ban
systemctl start fail2ban

# ── 7. Pull a default model (optional) ───────────────────────
echo ""
echo -e "${YELLOW}============================================================"
echo " OPTIONAL: Pull a model now?"
echo " Recommended: llama3.2 (2GB), mistral (4GB), llama3.1:8b (5GB)"
echo "============================================================${NC}"
read -r -p "Pull llama3.2 now? [Y/n]: " PULL_MODEL
if [[ "${PULL_MODEL:-Y}" =~ ^[Yy]$ ]]; then
  info "Pulling llama3.2 (this may take a few minutes)..."
  ollama pull llama3.2
  info "Model ready."
fi

# ── 8. Summary ─────────────────────────────────────────────────
PUBLIC_IP=$(curl -s --max-time 5 http://checkip.amazonaws.com/ || echo "<your-ec2-public-ip>")

echo ""
echo -e "${GREEN}============================================================"
echo " ✓  FIX-R EC2 AI Server setup complete!"
echo "============================================================${NC}"
echo ""
echo "  Public IP   : $PUBLIC_IP"
echo "  API Endpoint: http://$PUBLIC_IP"
echo "  API Key     : $API_KEY"
echo ""
echo "  Test with:"
echo "    curl http://$PUBLIC_IP/health"
echo ""
echo "  Add to FIX-R Admin → Servers:"
echo "    Name     : EC2 AI Server"
echo "    Base URL : http://$PUBLIC_IP"
echo "    Model    : llama3.2   (or whichever you pulled)"
echo "    API Key  : $API_KEY"
echo ""
echo "  API key is saved at: $API_KEY_FILE"
echo "  To add HTTPS, run:  sudo certbot --nginx -d your-domain.com"
echo ""
